# Generated by Django 5.1.7 on 2025-03-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='status',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='type_amount',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='updated_at',
        ),
    ]
