# Generated by Django 5.1.7 on 2025-03-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_delivery_created_at_remove_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(default='Received', max_length=20),
        ),
    ]
