# Generated by Django 5.1.7 on 2025-03-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delivery_type_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='warhouse_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
