# Generated by Django 5.1.7 on 2025-03-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_delivery_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'permissions': [('change_delivery_status', 'Can change delivery status')]},
        ),
    ]
