# Generated by Django 5.1.7 on 2025-03-24 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_delivery_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='type_amount',
        ),
    ]
